# My Properties 
webdriver.sampleresult_class=com.googlecode.jmeter.plugins.webdriver.sampler.SampleResultWithSubs
remote_hosts=192.168.4.5
server.rmi.ssl.keystore.type=JKS
server.rmi.ssl.keystore.file=rmi_keystore.jks
server.rmi.ssl.keystore.password=123456
server.rmi.ssl.keystore.alias=rmi
server.rmi.ssl.truststore.type=JKS
server.rmi.ssl.truststore.file=rmi_keystore.jks
server.rmi.ssl.truststore.password=123456
server.rmi.ssl.disable=true
httpsampler.ignore_failed_embedded_resources=true


# Required for Graphs 
jmeter.save.saveservice.bytes = true
# Only available with HttpClient4
#jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.label = true
jmeter.save.saveservice.latency = true
jmeter.save.saveservice.response_code = true
jmeter.save.saveservice.response_message = true
jmeter.save.saveservice.successful = true
jmeter.save.saveservice.thread_counts = true
jmeter.save.saveservice.thread_name = true
jmeter.save.saveservice.time = true
jmeter.save.saveservice.connect_time = true
jmeter.save.saveservice.assertion_results_failure_message = true
# the timestamp format must include the time and should include the date.
# For example the default, which is milliseconds since the epoch:
#jmeter.save.saveservice.timestamp_format = ms
# Or the following would also be suitable
jmeter.save.saveservice.timestamp_format = yyyy/MM/dd HH:mm:ss

# Graphs
jmeter.reportgenerator.overall_granularity=5000
jmeter.reportgenerator.report_title=Performance Test REPORT
jmeter.reportgenerator.graph.title=PT Report
jmeter.reportgenerator.apdex_satisfied_threshold=1500
jmeter.reportgenerator.apdex_tolerated_threshold=4000
jmeter.reportgenerator.exporter.html.property.output_dir=/tmp/test-report
jmeter.reportgenerator.exporter.html.filters_only_sample_series=true
